### ISSUE TITLE
OpenAT entry.. 

### ISSUE THREAD

**Issue by willwade** [AbilitySpectrum/Sensact#12]
Not really a issue! More a note really! We have entered both [Sensact](https://openassistive.org/item/Sensact/) and [Aural scanner](https://openassistive.org/item/Blink_aural_scanning_keyboard/) on [Open Assistive](https://openassistive.org/). You don't need to do anything but if you want to edit the entries feel free to - just do a PR on the project (Sensact: https://github.com/openassistive/OpenATFrontEnd/blob/master/content/item/Sensact.md & Blink Aural Scanner: https://github.com/openassistive/OpenATFrontEnd/blob/master/content/item/Blink_aural_scanning_keyboard.md/) 

Thanks for your work!

**Comment by ylh888** [comment]
Hi Will, Thanks for adding our projects to your site. OpenAT is a good repository that is sorely needed. Please private message me to discuss more.
